spring:
  config:
    import: optional:file:.env
  application:
    name: fairplay

  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  hashids:
    salt: ${HASHIDS_SALT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: 600000      # 10분(600,000 ms)
  refresh-token-validity-ms: 172800000  # 2일(172,800,000 ms)
  refresh-token-prefix: "refresh_token:"


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  client-secret: ${KAKAO_CLIENT_SECRET:}

cloud:
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME} # S3 버킷 이름
    region:
      static: ap-northeast-2 # ← 한국(서울) 리전으로 고정
      auto: false
    stack:
      auto: false # CloudFormation 스택 자동 생성 비활성화
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
