spring:
  application:
    name: fairplay

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/fairplay
    username: mydb
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  hashids:
    salt: tlmJA7J1RM4LScYySmSFG0F2NSl8QnqdncMkwVCVjrs=

  mail:
    host: smtp.gmail.com
    port: 587
    username: thdclgh0901@gmail.com
    password: gnth rnyz nrty velx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: KJbldsh2389dAjsdkljAD9821jhJHJJDHASjkllhHJksdhsuadhjku1l23jkh98AJA
  access-token-validity-ms: 600000 # 10분(600,000 ms)
  refresh-token-validity-ms: 172800000 # 2일(172,800,000 ms)
  refresh-token-prefix: "refresh_token:"

kakao:
  client-id: e34bd1d27d40bfefb5f832b63d51f80e
  redirect-uri: http://localhost:5173/auth/kakao/callback
  client-secret:
